language: cpp
os:
    - linux
    # - windows
dist: xenial
compiler: clang


services:
 - docker


before_install:
 # Prepare the docker image
 #- docker pull debian:sid
 #- docker build -t debian:sid .
 - if [ "$TRAVIS_OS_NAME" = "linux" ];
        docker pull thijswithaar/sid;
        docker run -it -d --name build thijswithaar/sid;
        docker exec build apt update -q;
        docker exec build apt upgrade -y;
   fi

install:
 # Copy source code to docker
 - if [ "$TRAVIS_OS_NAME" = "linux" ];
        docker cp ${TRAVIS_BUILD_DIR} build:${TRAVIS_BUILD_DIR};
   fi


script:
 - docker exec build cmake -DCMAKE_CXX_COMPILER=clang++-9 -DCMAKE_BUILD_TYPE=RELEASE -H${TRAVIS_BUILD_DIR} -B${TRAVIS_BUILD_DIR}/build
 - docker exec build cmake --build ${TRAVIS_BUILD_DIR}/build -- package test
 - docker cp build:${TRAVIS_BUILD_DIR}/build ${TRAVIS_BUILD_DIR}/build


before_deploy:
 - git config --local user.name "${GIT_USER}"
 - git config --local user.email "${GIT_EMAIL}"
 - export TRAVIS_TAG="0.1.${TRAVIS_BUILD_NUMBER}"
 - git tag "${TRAVIS_TAG}" "${TRAVIS_COMMIT}"


deploy:
 provider: releases
 tag_name: ${TRAVIS_TAG}
 target_commitish: "master"
 name: "${TRAVIS_TAG}: A new hope"
 api_key: ${GithubToken}
 file_glob: true
 file: "${TRAVIS_BUILD_DIR}/build/*.deb"
 overwrite: true
 skip_cleanup: true
 draft: false
