language: cpp
os:
    - linux
    # - windows
dist: xenial
compiler: clang

services:
 - docker

env:
  DOCKER_BUILD_DIR=/home/travis/CD-Grab

before_install:
 - docker pull thijswithaar/sid:local
 - docker run -it -d --user $(id -u):$(id -g) -v ${TRAVIS_BUILD_DIR}:${DOCKER_BUILD_DIR} -w ${DOCKER_BUILD_DIR} --name build thijswithaar/sid

script:
 - env
 - ls -alF ${TRAVIS_BUILD_DIR}
 - whoami
 - docker exec build ls -alF ${DOCKER_BUILD_DIR}
 - docker exec build whoami
 - docker exec build cmake -DCMAKE_CXX_COMPILER=clang++-9 -DCMAKE_BUILD_TYPE=RELEASE -H${DOCKER_BUILD_DIR} -B${DOCKER_BUILD_DIR}/build
 - docker exec build cmake --build ${DOCKER_BUILD_DIR}/build
 - docker exec build cmake --build ${DOCKER_BUILD_DIR}/build -- package test

deploy:
 provider: releases
 tag_name: ${TRAVIS_TAG}
 target_commitish: "master"
 name: "A New Hope"
 api_key: ${GithubToken}
 file_glob: true
 file: "${TRAVIS_BUILD_DIR}/build/*.deb"
 overwrite: true
 skip_cleanup: true
 draft: false
 on:
  tags: true
