language: cpp
os: linux
dist: xenial
compiler: clang


services:
 - docker


before_install:
 # Prepare the docker image
 #- docker pull debian:sid
 #- docker build -t debian:sid .
 - docker pull thijswithaar/sid
 - docker run -it -d --name build thijswithaar/sid

 # Get the latest and greatest
 - docker exec build apt update -q
 - docker exec build apt upgrade -y


install:
 # Copy source code to docker
 - docker cp "${TRAVIS_BUILD_DIR}" build:/repo


script:
 - docker exec build cmake -DCMAKE_CXX_COMPILER=clang++-9 -H/repo -B/repo.build
 - docker exec build cmake --build /repo.build -- package
 - docker cp build:/repo.build "${TRAVIS_BUILD_DIR}/build"


#before_deploy:
# - git config --local user.name "${GIT_USER}"
# - git config --local user.email "${GIT_EMAIL}"
## - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
# - export $TRAVIS_TAG="0.1"
# - git tag $TRAVIS_TAG


deploy:
 provider: releases
 tag_name: 0.11
 api_key: ${GithubToken}
 file_glob: true
 file: "${TRAVIS_BUILD_DIR}/build/*.deb"
 overwrite: true
 skip_cleanup: true
 draft: false
 #on.tags: true
