language: cpp
os: linux
dist: xenial
compiler: clang

addons:
  apt:
    packages:
      - cmake
      - libflac-dev
      - libopus-dev
      - qtbase5-dev

script:
    - cmake .
    - cmake --build .
