language: cpp
os: linux
dist: xenial
compiler: clang

addons:
  apt:
    packages:
      - cmake
      - ninja
      - libflac-dev
      - libopus-dev
      - qtbase5-dev

script:
    - mkdir build
    - cd build
    - cmake -GNinja ..
    - ninja
