language: cpp
os: linux
dist: xenial
compiler: clang

services:
 - docker

before_install:
 # Prepare the docker image
 - docker pull debian:sid
 - docker run -it -d --name build debian:sid

install:
 # Add repositories
 - docker exec build apt update -q
 - docker exec build apt install -y wget gnupg ca-certificates software-properties-common
 - docker exec build wget https://apt.llvm.org/llvm-snapshot.gpg.key
 - docker exec build apt-key add llvm-snapshot.gpg.key
 - docker exec build apt-add-repository "deb http://apt.llvm.org/unstable/ llvm-toolchain main"

 # Copy source code to docker
 - docker cp "${TRAVIS_BUILD_DIR}" build:/repo

 # Install required applications, libraries
 - docker exec build apt update -q
 - docker exec build apt install -y build-essential git cmake clang
 - docker exec build apt install -y libflac-dev libopus-dev libsoxr-dev qtbase5-dev libboost-all-dev

 # Catch2 is not yet in a repo, so build+install ourselves
 - docker exec build git clone https://github.com/catchorg/Catch2.git /catch2
 - docker exec build cmake -H/catch2 -B/catch2.build -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX=/usr
 - docker exec build cmake --build /catch2.build -- install

script:
 - docker exec build cmake -DCMAKE_CXX_COMPILER=clang++ -H/repo -B/repo.build
 - docker exec build cmake --build /repo.build -- package
 - docker cp build:/repo.build "${TRAVIS_BUILD_DIR}/build"

before_deploy:
 - git config --local user.name "${GIT_USER}"
 - git config --local user.email "${GIT_EMAIL}"
 - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
 - git tag $TRAVIS_TAG

deploy:
 provider: releases
 api_key: ${GithubToken}
 file_glob: true
 file: "${TRAVIS_BUILD_DIR}/build/*.deb"
 overwrite: true
 skip_cleanup: true
 draft: true
