image:
 - Visual Studio 2017

configuration:
 - release      # lower-case might be needed for VCPKG_BUILD_TYPE

platform:
 - x64

clone_folder: c:\projects\cd_grab

environment:
    VCPKG_DIR: C:\Tools\vcpkg
    VCPKG_DEFAULT_TRIPLET: x64-windows
    #CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    CMAKE_GENERATOR: Ninja
    QT_DIR: C:\Qt\latest\msvc2017_64

init:
 - echo %APPVEYOR_BUILD_WORKER_IMAGE%
 - echo %VCPKG_DIR%
 - echo %VCPKG_DEFAULT_TRIPLET%
 - echo %CMAKE_GENERATOR%
 #- echo %QT_DIR%
 #- dir C:\Qt
 #- dir "C:\Program Files (x86)\Microsoft Visual Studio"
 #- dir "C:\Program Files (x86)\Microsoft Visual Studio\2017"
 - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
 - echo.set(VCPKG_BUILD_TYPE %CONFIGURATION%)>> %VCPKG_DIR%\triplets\%PLATFORM%-windows.cmake
 - type %VCPKG_DIR%\triplets\x64-windows.cmake
 - set Path=%QT_DIR%\bin;%Path%

install:
 - cd c:\tools\vcpkg
 - git remote add twithaar https://github.com/ThijsWithaar/vcpkg.git
 - git fetch twithaar
 - git checkout twithaar/soxr -b soxr
 - vcpkg update
 #- vcpkg build opus
 - vcpkg install catch2 libflac opus soxr
 - vcpkg install boost-beast boost-crc boost-filesystem boost-format boost-serialization boost-system
 #- vcpkg install qt5 # This one takes too long, use a pre-compiled version
 - vcpkg integrate install

before_build:
 - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_PREFIX_PATH=%QT_DIR% -DCMAKE_BUILD_TYPE=RELEASE -H%APPVEYOR_BUILD_FOLDER% -B%APPVEYOR_BUILD_FOLDER%/build
 - dir %APPVEYOR_BUILD_FOLDER%\build

build_script:
 - cmake --build %APPVEYOR_BUILD_FOLDER%/build -- package test

#build:
#  project: c:\projects\cd_grab\build\PACKAGE.vcxproj

artifacts:
 - path: build\*.exe
   name: windows_installer

deploy:
  release: 0.1.62 #-$(appveyor_build_version)
  description: Attack of the Clones
  provider: GitHub
  auth_token:
    secure: kb0a0ovLyJt0Um5ZFdnFOxalcytOF0kqX1vR+/Q+hMKnQsrVA5z28ivHaNoFVN3r
  #artifact: windows_installer
  draft: false
  #force_update: true
  on:
    branch: master

cache:
 - c:\tools\vcpkg\installed\
