image:
 - Visual Studio 2017
 - ubuntu1804

configuration:
 - release      # lower-case might be needed for VCPKG_BUILD_TYPE

platform:
 - x64

clone_folder: c:\projects\cd_grab

environment:
    VCPKG_DIR: C:\Tools\vcpkg
    VCPKG_DEFAULT_TRIPLET: x64-windows
    #CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    CMAKE_GENERATOR: Ninja
    QT_DIR: C:\Qt\latest\msvc2017_64

init:
 - echo %APPVEYOR_BUILD_WORKER_IMAGE%
 - echo %VCPKG_DIR%
 - echo %VCPKG_DEFAULT_TRIPLET%
 - echo %CMAKE_GENERATOR%
 #- echo %QT_DIR%
 #- dir C:\Qt
 #- dir "C:\Program Files (x86)\Microsoft Visual Studio"
 #- dir "C:\Program Files (x86)\Microsoft Visual Studio\2017"
 - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
 - cmd: echo.set(VCPKG_BUILD_TYPE %CONFIGURATION%)>> %VCPKG_DIR%\triplets\%PLATFORM%-windows.cmake
 - cmd: type %VCPKG_DIR%\triplets\x64-windows.cmake
 - cmd: set Path=%QT_DIR%\bin;%Path%

install:
 - cmd: cd c:\tools\vcpkg
 - cmd: git remote add twithaar https://github.com/ThijsWithaar/vcpkg.git
 - cmd: git fetch twithaar
 - cmd: git checkout twithaar/soxr -b soxr
 - cmd: vcpkg update
 - cmd: vcpkg install catch2 libflac opus soxr
 - cmd: vcpkg install boost-beast boost-crc boost-filesystem boost-format boost-serialization boost-system
 - cmd: vcpkg integrate install
 # ubuntu
 - sh: apt upgrade -y
 - sh: apt install -y build-essential git cmake clang-9
 - sh: apt install -y libflac-dev libopus-dev libsoxr-dev qtbase5-dev qttools5-dev libboost-all-dev


before_build:
 - cmd: cmake -G "%CMAKE_GENERATOR%" -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_PREFIX_PATH=%QT_DIR% -DCMAKE_BUILD_TYPE=RELEASE -H%APPVEYOR_BUILD_FOLDER% -B%APPVEYOR_BUILD_FOLDER%/build
 - sh: cmake -DCMAKE_CXX_COMPILER=clang++-9 -DCMAKE_BUILD_TYPE=RELEASE -H%APPVEYOR_BUILD_FOLDER% -B%APPVEYOR_BUILD_FOLDER%/build
 - dir %APPVEYOR_BUILD_FOLDER%\build

build_script:
 - cmake --build %APPVEYOR_BUILD_FOLDER%/build -- package

test_script:
 - cmake --build %APPVEYOR_BUILD_FOLDER%/build -- test

artifacts:
 - path: build\*.exe
   name: windows_installer

#skip_tags: true

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: Attack of the Clones
  provider: GitHub
  auth_token:
    secure: kb0a0ovLyJt0Um5ZFdnFOxalcytOF0kqX1vR+/Q+hMKnQsrVA5z28ivHaNoFVN3r
  artifact: windows_installer
  draft: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true

cache:
 - c:\tools\vcpkg\installed\
